name: Generate Datas

on:
  schedule: # execute every 24 hours
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: generate python_cobrinha_tchola.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/python_cobrinha_tchola.svg?palette=github-dark&color_snake=green&color_dots=#1c2e4f,#214377,#2159a2,#1b70d0,#0088ff

          
          
      - name: push python_cobrinha_tchola.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
